
export const CREATE_USER_API = "https://us4okg8.219.93.129.146.sslip.io/contacts"
export const GET_ORDER_ITEMS = "https://storesdemo.morr.biz/wp-json/woomorrintegration/v1/orderproducts?order_per_page=10"
export const GET_CONTACTS_API = "https://amogademo-postgrest.morr.biz/user_catalog"
export const GET_ONE_CONTACT_API = "https://amogademo-postgrest.morr.biz/user_catalog?user_catalog_id=eq."
export const GET_GROUPS="https://amogademo-postgrest.morr.biz/chat_group"
export const GET_SINGLE_GROUP="https://amogademo-postgrest.morr.biz/chat_group?chat_group_id=eq."
export const GET_CHAT_GROUP_USERS="https://amogademo-postgrest.morr.biz/chat_group_users"
export const GET_CHAT_MESSAGES="https://amogademo-postgrest.morr.biz/chat_message"
export const CREATE_CHAT_MESSAGE="https://amogademo-postgrest.morr.biz/chat_message"
export const GET_USERS_OF_GROUP="https://amogademo-postgrest.morr.biz/chat_group_users?group_id=eq."
export const DELETE_USERS_FROM_GROUP="https://amogademo-postgrest.morr.biz/chat_group_users"
export const BOM_RAW_URL="https://amogademo-postgrest.morr.biz/bom_raw"
export const GET_FILE_MESSAGES = "https://amogademo-postgrest.morr.biz/document"
export const LOG_USERS_API = "https://amogademo-postgrest.morr.biz/user_log"
export const GET_EMAILS="https://amogademo-postgrest.morr.biz/email"
export const CREATE_IMAP_DETAILS_URL = "https://amogademo-postgrest.morr.biz/user_catalog_data"
export const CREATE_EMAIL_ATTACHMENT_URL = "https://amogademo-postgrest.morr.biz/email_attachment"