import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/layout/topNav";
import Providers from "@/components/layout/providers";
import { auth } from "@/auth";
import { headers } from "next/headers";
import NextTopLoader from "nextjs-toploader"
import { ThemeProvider } from "@/components/context/themeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const headersList = headers();
  const pathname = headersList.get('x-pathname') || '/';

  const hideTopBar = pathname === '/login' || pathname === '/storejoin';

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader />
        <Providers session={session}>           
        <ThemeProvider>
          <div>
            {!hideTopBar && <TopBar />}
            <div className="pt-[20%] md:pt-0">
            {children}
            </div>
          </div>        
        </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
