name: Deploy Next.js App to Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3 to avoid Node.js 12 deprecation

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to v3 for Node.js setup
        with:
          node-version: '20.15.0'  # Set to Node.js 20 (to match your server version)

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Updated to v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t amogademo/nextjs-app .
          docker push amogademo/nextjs-app

      - name: SSH into server and setup Traefik and pull the Docker image
        uses: appleboy/ssh-action@v0.1.5  # Correct version for the SSH action
        with:
          host: 219.93.129.48
          username: administrator
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 2222
          script: |
            # Navigate to the directory containing the Traefik docker-compose.yml
            cd ~/traefik
            
            # Start Traefik if it's not already running
            docker-compose up -d
            
            # Pull the latest Docker image for the Next.js app
            docker pull amogademo/nextjs-app
            
            # Navigate to the directory containing your Next.js app docker-compose.yml
            cd ~/nextjs-app
            
            # Stop the current Next.js app if it's running
            docker-compose down
            
            # Start the Next.js app in detached mode
            docker-compose up -d
