name: Deploy Next.js App to Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t amogademo/amogademo .

    - name: Push Docker image
      run: |
        docker push amogademo/amogademo

    - name: Copy docker-compose.yml to server
      uses: appleboy/scp-action@master
      with:
        host: 219.93.129.48
        username: administrator
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 2222
        source: "docker-compose.yml"
        target: "/path/on/server"

    - name: SSH into server to deploy the app
      uses: appleboy/ssh-action@master
      with:
        host: 219.93.129.48
        username: administrator
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 2222
        script: |
          docker pull amogademo/amogademo
          docker-compose down
          docker-compose up -d
