name: Deploy Next.js App to Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This is already the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # This is already the latest version
        with:
          node-version: '20'  # Updated to 20 for compatibility

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # This is already the latest version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t amogademo/nextjs-app .
          docker push amogademo/nextjs-app

      - name: SSH into server and pull the Docker image
        uses: appleboy/ssh-action@v0.1.5  # This version is correct
        with:
          host: 219.93.129.48
          username: administrator
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 2222
          script: |
            docker pull amogademo/nextjs-app
            docker-compose down
            docker-compose up -d
